package sprite

import (
	"fmt"
	"github.com/celskeggs/mediator/platform/types"
	"strings"
)

type Sound struct {
	File    string `json:"file"`
	Repeat  bool   `json:"repeat"`
	Wait    bool   `json:"wait"`
	Channel uint   `json:"channel"`
	Volume  uint   `json:"volume"`
}

var _ types.Value = &Sound{}

func (s Sound) Var(name string) types.Value {
	switch name {
	case "file":
		return types.String(s.File)
	case "repeat":
		return types.FromBool(s.Repeat)
	case "wait":
		return types.FromBool(s.Wait)
	case "channel":
		return types.Int(s.Channel)
	case "volume":
		return types.Int(s.Volume)
	default:
		panic("no such field " + name + " on /sound")
	}
}

func (s Sound) SetVar(name string, value types.Value) {
	switch name {
	case "file":
		s.File = types.Unstring(value)
	case "repeat":
		s.Repeat = types.AsBool(value)
	case "wait":
		s.Wait = types.AsBool(value)
	case "channel":
		s.Channel = uint(types.Unint(value))
	case "volume":
		s.Volume = uint(types.Unint(value))
	default:
		panic("no such field " + name + " on /sound")
	}
}

func (s Sound) Invoke(name string, parameters ...types.Value) types.Value {
	panic("no such proc " + name + " on /sound")
}

func (s Sound) String() string {
	return fmt.Sprintf("[sound: %q]", s.File)
}

func (s Sound) FixMID() Sound {
	if strings.HasSuffix(s.File, ".mid") {
		// ogg conversion will be autogenerated
		s.File = s.File[:len(s.File)-4] + ".ogg"
	}
	return s
}
